### ISSUE TITLE
404 not found: index.php/loginpopupsave

### ISSUE THREAD

**Issue by savishy** [savishy/docker-sentrifugo#10]
- nginx and php-fpm have been properly configured
- I am able to proceed with sentrifugo web installation properly.
- after that, I visit index.php to login 
- I login successfully, and then see this screen:

![image](https://cloud.githubusercontent.com/assets/13379978/17289370/0fe0a862-57f7-11e6-900f-de70aab66186.png)

**Comment by savishy** [comment]
It is possible this is some weird php7 issue. Sentrifugo does not support PHP 7.0 as of date - [ref](https://sourceforge.net/p/sentrifugo/tickets/21/) - so I can expect other issues to crop up later.

Trying out php5.

**Comment by savishy** [comment]
Work for this is being tracked in `issue-10` branch.

**Comment by hakarune** [comment]
I'm on php 7.0 and I just got this error today. Is this not fixed 4 years after the initial issue? Do I need to upgrade to 7.1 or something?

**Comment by savishy** [comment]
I don't maintain this repo any more. You are welcome to fork and try out a solution though.
