### ISSUE TITLE
Repository is not working 

### ISSUE THREAD

**Issue by avi7611** [savishy/docker-sentrifugo#16]
im getting following error while building up.

Step 5/23 : RUN add-apt-repository ppa:ondrej/php
 ---> Running in e3c3fe826ceb
 Co-installable PHP versions: PHP 5.6, PHP 7.x and most requested extensions are included. Only Supported Versions of PHP (http://php.net/supported-versions.php) for Supported Ubuntu Releases (https://wiki.ubuntu.com/Releases) are provided. Don't ask for end-of-life PHP versions or Ubuntu release, they won't be provided.

Debian oldstable and stable packages are provided as well: https://deb.sury.org/#debian-dpa

You can get more information about the packages at https://deb.sury.org

IMPORTANT: The <foo>-backports is now required on older Ubuntu releases.

BUGS&FEATURES: This PPA now has a issue tracker:
https://deb.sury.org/#bug-reporting

CAVEATS:
1. If you are using php-gearman, you need to add ppa:ondrej/pkg-gearman
2. If you are using apache2, you are advised to add ppa:ondrej/apache2
3. If you are using nginx, you are advised to add ppa:ondrej/nginx-mainline
   or ppa:ondrej/nginx

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating regularly: https://donate.sury.org/

WARNING: add-apt-repository is broken with non-UTF-8 locales, see
https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
gpg: keyring `/tmp/tmpvdnlkcab/secring.gpg' created
gpg: keyring `/tmp/tmpvdnlkcab/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpvdnlkcab/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)
ERROR: Service 'sentrifugo-app' failed to build : The command '/bin/sh -c add-apt-repository ppa:ondrej/php' returned a non-zero code: 1

**Comment by savishy** [comment]
Thanks for reporting! I don't maintain this repo any more. You are welcome to fork and develop it though.
